from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

module chandra_data_workflow:
    snakefile:
        # here, plain paths, URLs and the special markers for code hosting providers (see below) are possible.
        github("adonath/snakemake-workflow-chandra", path="workflow/Snakefile", branch="main")
    config: config["chandra-data"]

use rule * from chandra_data_workflow as chandra_data_*

include: "rules/run-jolideco.smk"

rule all:
    input: 
    default_target: True