# Conda environment for reducing fermi data
name: jolideco-chandra-examples

channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python
  - snakemake=8.12.0
  - pydantic<2.0
  - astropy>=5.2.0
  - regions>=0.5
  - nbconvert
  - ipython
  - ipykernel
  - gammapy>=1.0
  - pytorch=2.3
  - pytorch-cuda=12.1
