chandra-data:
  name: e0102-broadband
  path_data: data
  obs_ids:
    - 15559
    - 15557
    - 15556
    - 15558
    - 15555
    - 22811
    - 8365 
    - 9694 
    - 6766 
    - 25620
    - 22812
    - 24578
    - 21806
    - 22807
    - 21805
    - 20641
    - 19852
    - 19851
    - 18420
    - 18419
    - 15467
    - 14258
    - 13093
    - 20640
    - 11957
    - 24579
    - 22806
    - 6759 
    - 25619
    - 17380
    - 26987
    - 25618
    - 22810
    - 22805
    - 21804
    - 20639
    - 19850
    - 18418
    - 24577
    - 27761
    - 26989
  obs_id_ref: 15557
  roi:
    center:
      frame: icrs
      lon: "01h04m02.00s"
      lat: "-72d01m52.30s"
    width: 1 arcmin
    bin_size: 0.25
    energy_range:
      min: 0.5 keV
      max: 7 keV
  psf_simulator: marx
  irfs:
    e0102:
      spectrum:
        center:
          frame: icrs
          lon: "01h04m02.00s"
          lat: "-72d01m52.30s"
        radius: 0.3 arcmin
        energy_range:
          min: 0.5 keV
          max: 7.0 keV
        energy_groups: 5
        energy_step: 0.01
      psf:
        blur: 0.07
        readout_streak: false
        pileup: false
        extended: true
        minsize: 125
        numiter: 100
  ciao:
    chandra_repro:
      cleanup: true
      clobber: true
