chandra-data:
  name: e0102
  path_data: data
  obs_ids:
    - 1308
    - 1311
    - 1530
    - 1531
    - 2843
    - 2844
    - 2850
    - 2851
    - 3519
    - 3520
    - 3544
    - 3545
    - 5123
    - 5124
    - 5130
    - 5131
    - 6042
    - 6043
    - 6074
    - 6075
    - 6758
    - 6759
    - 6765
    - 8365
    - 9694
  obs_id_ref: 8365
  roi:
    center:
      frame: icrs
      lon: "01h04m02.00s"
      lat: "-72d01m52.30s"
    width: 1 arcmin
    bin_size: 0.5
    energy_range:
      min: 0.5 keV
      max: 7 keV
  psf_simulator: marx
  irfs:
    e0102:
      spectrum:
        center:
          frame: icrs
          lon: "01h04m02.00s"
          lat: "-72d01m52.30s"
        radius: 0.3 arcmin
        energy_range:
          min: 0.5 keV
          max: 7.0 keV
        energy_groups: 5
        energy_step: 0.01
      psf:
        blur: 0.07
        readout_streak: false
        pileup: false
        extended: true
        minsize: 125
        numiter: 500
  ciao:
    chandra_repro:
      cleanup: true
      clobber: true
